- name: kubeadm
  hosts: all
  roles:
    - kubeadm

  post_tasks:
    - name: verify kubeadm
      command: >
        kubectl get nodes -o name
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      become: true
      changed_when: false
      delegate_to: "{{ groups['master'][0] }}"
      failed_when: kubectl_get_nodes.rc != 0 or "node/" + inventory_hostname not in kubectl_get_nodes.stdout_lines
      register: kubectl_get_nodes
      tags:
        - verify
