- import_tasks: kubeadm_config.yml

# TODO: do a more thorough test here

- name: init check previous run
  ansible.builtin.stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  register: kube_apiserver_stat

- name: init run
  ansible.builtin.command: >
    kubeadm init --config /var/lib/kubeadm/config.yaml
  become: true
  register: kubeadm_init_result
  when: 
    - not kube_apiserver_stat.stat.exists

- name: init print result
  ansible.builtin.debug:
    var: kubeadm_init_result
  when: 
    - not kube_apiserver_stat.stat.exists