- name: init create config directory
  ansible.builtin.file:
    path: /var/lib/kubeadm
    state: directory
    owner: root
  become: true

# NOTE: this is required for the next template task
# since it iterates over controller network facts
- name: init gather facts about controller nodes
  ansible.builtin.setup:
    gather_subset: network
  delegate_facts: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['master'] }}"

- name: init generate kubelet config for kubeadm
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /var/lib/kubeadm/config.yaml
    owner: root
    group: root
    mode: "0600"
  become: true

# TODO: do a more thorough test here

- name: init check previous run
  ansible.builtin.stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  become: true
  register: kube_apiserver_stat

- name: init run
  ansible.builtin.command: >
    kubeadm init --config /var/lib/kubeadm/config.yaml
  become: true
  register: kubeadm_init_result
  when: 
    - not kube_apiserver_stat.stat.exists

- name: init print result
  ansible.builtin.debug:
    var: kubeadm_init_result
  when: 
    - not kube_apiserver_stat.stat.exists