- name: init create config directory
  ansible.builtin.file:
    path: /var/lib/kubeadm
    state: directory
    owner: root
  become: true

# NOTE: this is required for the next template task
# since it iterates over controller network facts
- name: init gather facts about controller nodes
  ansible.builtin.setup:
    gather_subset: network
  delegate_facts: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['master'] }}"
  when: inventory_hostname in groups['master']

- name: init generate kubelet config for kubeadm
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /var/lib/kubeadm/config.yaml
    owner: root
    group: root
    mode: "0600"
  become: true
