- import_tasks: kubeadm_join_tokens.yml
  run_once: true

- ansible.builtin.command: >
    kubectl get nodes -o name
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true
  changed_when: false
  delegate_to: "{{ groups['master'][0] }}"
  register: kubectl_get_nodes

- include_tasks: kubeadm_join_master.yml
  when:
    - inventory_hostname in groups['master']
    - ("node/" + ansible_hostname not in kubectl_get_nodes.stdout_lines)

- include_tasks: kubeadm_join_worker.yml
  when:
    - inventory_hostname in groups['worker']
    - inventory_hostname not in groups['master']
    - ("node/" + ansible_hostname not in kubectl_get_nodes.stdout_lines)

- name: bind kubelet to internal address
  ansible.builtin.lineinfile:
    path: /var/lib/kubelet/config.yaml
    line: "address: {{ internal_address }}"
    insertbefore: BOF
  become: true
  notify: restart kubelet service
