- import_tasks: kubeadm_install.yml

- name: download controller images
  ansible.builtin.command: >
    kubeadm config images pull
  become: true
  changed_when: false
  when: inventory_hostname in groups['master']

- include_tasks: kubeadm_init.yml
  when: inventory_hostname in groups['master'][0]

- import_tasks: kubeadm_join.yml
