- name: download flannel manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: /tmp/kube-flannel.yaml
    owner: root
    group: root
    mode: "0600"
  become: true

- name: patch flannel manifest
  ansible.builtin.lineinfile:
    path: /tmp/kube-flannel.yaml
    regexp: '"Network":'
    line: '      "Network": "{{ pod_subnet }}",'
  become: true

- name: patch flannel manifest
  ansible.builtin.lineinfile:
    path: /tmp/kube-flannel.yaml
    line: '        - --iface={{ internal_interface }}'
    insertafter: '- --ip-masq'
  become: true

- name: apply calico manifest
  ansible.builtin.command: >
    kubectl apply -f /tmp/kube-flannel.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true
